// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportIcons(arg1:main.ExportParams):Promise<string>;

export function LoadImageByPath(arg1:string):Promise<main.ImageInfo>;

export function OpenImageDialog():Promise<main.ImageInfo>;
