// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportIcons(arg1) {
  return window['go']['main']['App']['ExportIcons'](arg1);
}

export function LoadImageByPath(arg1) {
  return window['go']['main']['App']['LoadImageByPath'](arg1);
}

export function OpenImageDialog() {
  return window['go']['main']['App']['OpenImageDialog']();
}
